"""Add cascade delete from underlying_holdings to holdings

Revision ID: 242d14b25442
Revises: 6efe15029b9c
Create Date: 2026-02-02 09:23:58.202325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242d14b25442'
down_revision: Union[str, Sequence[str], None] = '6efe15029b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('underlying_holdings_holding_id_fkey'), 'underlying_holdings', type_='foreignkey')
    op.create_foreign_key(None, 'underlying_holdings', 'holdings', ['holding_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'underlying_holdings', type_='foreignkey')
    op.create_foreign_key(op.f('underlying_holdings_holding_id_fkey'), 'underlying_holdings', 'holdings', ['holding_id'], ['id'])
    # ### end Alembic commands ###
