"""add symbol_sector_cache table

Revision ID: 326b9e97036b
Revises: 8cfecf71142c
Create Date: 2026-02-09 22:13:12.291991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '326b9e97036b'
down_revision: Union[str, Sequence[str], None] = '8cfecf71142c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbol_sector_cache',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('weightings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_symbol_sector_cache_symbol'), 'symbol_sector_cache', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symbol_sector_cache_symbol'), table_name='symbol_sector_cache')
    op.drop_table('symbol_sector_cache')
    # ### end Alembic commands ###
