"""rename change_percent to all_time, add daily fields

Revision ID: 443257eb5360
Revises: 5770fc71bc66
Create Date: 2026-01-28 20:02:40.445515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443257eb5360'
down_revision: Union[str, Sequence[str], None] = '5770fc71bc66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('all_time_change_percent', sa.Float(), nullable=True))
    op.add_column('holdings', sa.Column('all_time_gain_loss', sa.Float(), nullable=True))
    op.drop_column('holdings', 'change_percent')
    op.drop_column('holdings', 'gain_loss')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('gain_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('holdings', sa.Column('change_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('holdings', 'all_time_gain_loss')
    op.drop_column('holdings', 'all_time_change_percent')
    # ### end Alembic commands ###
