"""add daily change columns to holdings

Revision ID: 5770fc71bc66
Revises: 84887150a975
Create Date: 2026-01-28 19:25:06.008905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5770fc71bc66'
down_revision: Union[str, Sequence[str], None] = '84887150a975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('daily_change', sa.Float(), nullable=True))
    op.add_column('holdings', sa.Column('daily_change_percent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holdings', 'daily_change_percent')
    op.drop_column('holdings', 'daily_change')
    # ### end Alembic commands ###
