"""add dividend manual override flag to holdings

Revision ID: 6c280403bbc9
Revises: 98745c85a6ef
Create Date: 2026-02-13 13:05:54.123182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c280403bbc9'
down_revision: Union[str, Sequence[str], None] = '98745c85a6ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('is_dividend_manual', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holdings', 'is_dividend_manual')
    # ### end Alembic commands ###
