"""add allocation_percent to underlying_holdings

Revision ID: 6efe15029b9c
Revises: f5dbd0e7395c
Create Date: 2026-02-01 23:58:44.033476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6efe15029b9c'
down_revision: Union[str, Sequence[str], None] = 'f5dbd0e7395c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('underlying_holdings', sa.Column('allocation_percent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('underlying_holdings', 'allocation_percent')
    # ### end Alembic commands ###
