"""add day_chart to holding

Revision ID: 8cfecf71142c
Revises: b1dd0f5cca44
Create Date: 2026-02-06 20:32:45.990433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cfecf71142c'
down_revision: Union[str, Sequence[str], None] = 'b1dd0f5cca44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('day_chart', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holdings', 'day_chart')
    # ### end Alembic commands ###
