"""Add last_price_update to Holding

Revision ID: 9a50ee91a6dc
Revises: aab33c6de7ee
Create Date: 2026-02-02 15:56:57.548805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a50ee91a6dc'
down_revision: Union[str, Sequence[str], None] = 'aab33c6de7ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('last_price_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holdings', 'last_price_update')
    # ### end Alembic commands ###
