"""add portfolio and global history tables

Revision ID: 9e26b2e7dcaa
Revises: 9b6c001b8157
Create Date: 2026-02-03 12:09:58.218423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e26b2e7dcaa'
down_revision: Union[str, Sequence[str], None] = '9b6c001b8157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('daily_change', sa.Float(), nullable=True),
    sa.Column('daily_percent', sa.Float(), nullable=True),
    sa.Column('all_time_gain', sa.Float(), nullable=True),
    sa.Column('all_time_percent', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_history_id'), 'global_history', ['id'], unique=False)
    op.create_index(op.f('ix_global_history_timestamp'), 'global_history', ['timestamp'], unique=False)
    op.create_table('portfolio_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('daily_change', sa.Float(), nullable=True),
    sa.Column('daily_percent', sa.Float(), nullable=True),
    sa.Column('all_time_gain', sa.Float(), nullable=True),
    sa.Column('all_time_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_history_id'), 'portfolio_history', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_history_timestamp'), 'portfolio_history', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_history_timestamp'), table_name='portfolio_history')
    op.drop_index(op.f('ix_portfolio_history_id'), table_name='portfolio_history')
    op.drop_table('portfolio_history')
    op.drop_index(op.f('ix_global_history_timestamp'), table_name='global_history')
    op.drop_index(op.f('ix_global_history_id'), table_name='global_history')
    op.drop_table('global_history')
    # ### end Alembic commands ###
