"""Add display_order to portfolios for server-side ordering

Revision ID: aab33c6de7ee
Revises: 242d14b25442
Create Date: 2026-02-02 13:47:15.590791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aab33c6de7ee'
down_revision: Union[str, Sequence[str], None] = '242d14b25442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('display_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'display_order')
    # ### end Alembic commands ###
