"""Add is_eod flag to global_history

Revision ID: b1dd0f5cca44
Revises: 9e26b2e7dcaa
Create Date: 2026-02-03 15:25:31.128550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1dd0f5cca44'
down_revision: Union[str, Sequence[str], None] = '9e26b2e7dcaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_history', sa.Column('is_eod', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_history', 'is_eod')
    # ### end Alembic commands ###
