"""add is_dividend_manual to holdings

Revision ID: db16bd51c2e1
Revises: 6c280403bbc9
Create Date: 2026-02-13 13:26:22.081300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db16bd51c2e1'
down_revision: Union[str, Sequence[str], None] = '6c280403bbc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
