"""add is_default to portfolios

Revision ID: f5dbd0e7395c
Revises: 443257eb5360
Create Date: 2026-01-29 00:04:26.405741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5dbd0e7395c'
down_revision: Union[str, Sequence[str], None] = '443257eb5360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.alter_column('portfolios', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolios', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('portfolios', 'is_default')
    # ### end Alembic commands ###
